### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers.models.resnet'

### ISSUE THREAD

**Issue by Jessegator** [IBM/BadDiffusion#1]
Hi, thank you for this interesting work. I was trying to run this code to learn more details about your paper but encountered the following error. it seems like some .py files have been removed from the original _diffusers_ library. I replaced the file _diffusers_  in this repo with the official one,  but still failed. I was wondering if you could help check on this issue? Thank you very much.

Traceback (most recent call last):
  File "baddiffusion.py", line 261, in <module>
    from diffusers.hub_utils import init_git_repo, push_to_hub
  File "D:\Anaconda3\envs\diff\lib\site-packages\diffusers\__init__.py", line 21, in <module>
    from .models import AutoencoderKL, UNet2DConditionModel, UNet2DModel, VQModel
  File "D:\Anaconda3\envs\diff\lib\site-packages\diffusers\models\__init__.py", line 19, in <module>
    from .unet_2d import UNet2DModel
  File "D:\Anaconda3\envs\diff\lib\site-packages\diffusers\models\unet_2d.py", line 24, in <module>
    from .unet_blocks import UNetMidBlock2D, get_down_block, get_up_block
  File "D:\Anaconda3\envs\diff\lib\site-packages\diffusers\models\unet_blocks.py", line 19, in <module>
    from .resnet import Downsample2D, FirDownsample2D, FirUpsample2D, ResnetBlock2D, Upsample2D
ModuleNotFoundError: No module named 'diffusers.models.resnet'
Traceback (most recent call last):
  File "baddiffusion.py", line 261, in <module>
    from diffusers.hub_utils import init_git_repo, push_to_hub
  File "D:\Anaconda3\envs\diff\lib\site-packages\diffusers\__init__.py", line 21, in <module>
    from .models import AutoencoderKL, UNet2DConditionModel, UNet2DModel, VQModel
  File "D:\Anaconda3\envs\diff\lib\site-packages\diffusers\models\__init__.py", line 19, in <module>
    from .unet_2d import UNet2DModel
  File "D:\Anaconda3\envs\diff\lib\site-packages\diffusers\models\unet_2d.py", line 24, in <module>
    from .unet_blocks import UNetMidBlock2D, get_down_block, get_up_block
  File "D:\Anaconda3\envs\diff\lib\site-packages\diffusers\models\unet_blocks.py", line 19, in <module>
    from .resnet import Downsample2D, FirDownsample2D, FirUpsample2D, ResnetBlock2D, Upsample2D
ModuleNotFoundError: No module named 'diffusers.models.resnet'

**Comment by FrankCCCCC** [comment]
Hi, thank you for being interested in our work!!! The ``library`` doesn't support ``diffusers.hub_utils`` anymore. Thus, I remove the dependency from the file ``baddiffusion.py``. Please try it again. Let me know if there is further issues.

**Comment by Jessegator** [comment]
Thanks for helping. The code can run successfully after I added in the directory `diffusers/src/diffusers/models/` the following Python files: `resnet.py`, `resnet_flax.py`. They can be directly copied from the official library. Again, nice work!!

**Comment by FrankCCCCC** [comment]
Great~ Please feel free to contact me if there are any issue.

**Comment by FrankCCCCC** [comment]
Added Python files: ``resnet.py``, ``resnet_flax.py`` in the directory diffusers/src/diffusers/models/ the following
