### ISSUE TITLE
cannot import name 'DPMSolverMultistepScheduler' from 'diffusers'

### ISSUE THREAD

**Issue by hellotohere** [IBM/BadDiffusion#7]
Hi, I'm interested in your work, but  When running the command `python baddiffusion.py --project default --mode train+measure --dataset CIFAR10 --batch 128 --epoch 50 --poison_rate 0.1 --trigger BOX_14 --target HAT --ckpt DDPM-CIFAR10-32 --fclip o -o --gpu 0`, I meet the error: 
`Traceback (most recent call last):
  File "/home/phd/code_phd/badDiffusion/baddiffusion.py", line 268, in <module>
    from model import DiffuserModelSched, batch_sampling, batch_sampling_save
  File "/home/phd/code_phd/badDiffusion/model.py", line 466, in <module>
    from diffusers import UNet2DModel, DDPMScheduler, DDIMScheduler, DPMSolverMultistepScheduler, UniPCMultistepScheduler, PNDMScheduler, DEISMultistepScheduler, HeunDiscreteScheduler, LMSDiscreteScheduler, ScoreSdeVeScheduler, KarrasVeScheduler, DiffusionPipeline, DDPMPipeline, DDIMPipeline, PNDMPipeline, ScoreSdeVePipeline, LDMPipeline, KarrasVePipeline
ImportError: cannot import name 'DPMSolverMultistepScheduler' from 'diffusers' (/home/phd/conda/envs/baddif/lib/python3.9/site-packages/diffusers/__init__.py)`
please  what should I do to solve this problem?

**Comment by hellotohere** [comment]
> Hi, I'm interested in your work, but When running the command `python baddiffusion.py --project default --mode train+measure --dataset CIFAR10 --batch 128 --epoch 50 --poison_rate 0.1 --trigger BOX_14 --target HAT --ckpt DDPM-CIFAR10-32 --fclip o -o --gpu 0`, I meet the error: `Traceback (most recent call last): File "/home/phd/code_phd/badDiffusion/baddiffusion.py", line 268, in <module> from model import DiffuserModelSched, batch_sampling, batch_sampling_save File "/home/phd/code_phd/badDiffusion/model.py", line 466, in <module> from diffusers import UNet2DModel, DDPMScheduler, DDIMScheduler, DPMSolverMultistepScheduler, UniPCMultistepScheduler, PNDMScheduler, DEISMultistepScheduler, HeunDiscreteScheduler, LMSDiscreteScheduler, ScoreSdeVeScheduler, KarrasVeScheduler, DiffusionPipeline, DDPMPipeline, DDIMPipeline, PNDMPipeline, ScoreSdeVePipeline, LDMPipeline, KarrasVePipeline ImportError: cannot import name 'DPMSolverMultistepScheduler' from 'diffusers' (/home/phd/conda/envs/baddif/lib/python3.9/site-packages/diffusers/__init__.py)` please what should I do to solve this problem?

i solve the problem by the command `pip install --upgrade diffusers[torch]`, but then a new problem occurs :
`Traceback (most recent call last):
  File "/home/phd/conda/envs/baddif/lib/python3.9/site-packages/diffusers/utils/import_utils.py", line 684, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/phd/conda/envs/baddif/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/phd/conda/envs/baddif/lib/python3.9/site-packages/diffusers/models/unet_2d.py", line 24, in <module>
    from .unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
  File "/home/phd/conda/envs/baddif/lib/python3.9/site-packages/diffusers/models/unet_2d_blocks.py", line 23, in <module>
    from .attention import AdaGroupNorm
  File "/home/phd/conda/envs/baddif/lib/python3.9/site-packages/diffusers/models/attention.py", line 22, in <module>
    from .attention_processor import Attention
  File "/home/phd/conda/envs/baddif/lib/python3.9/site-packages/diffusers/models/attention_processor.py", line 24, in <module>
    from .lora import LoRACompatibleLinear, LoRALinearLayer
  File "/home/phd/conda/envs/baddif/lib/python3.9/site-packages/diffusers/models/lora.py", line 21, in <module>
    from ..loaders import PatchedLoraProjection, text_encoder_attn_modules, text_encoder_mlp_modules
  File "/home/phd/conda/envs/baddif/lib/python3.9/site-packages/diffusers/loaders.py", line 47, in <module>
    from accelerate.hooks import AlignDevicesHook, CpuOffload, remove_hook_from_module
ImportError: cannot import name 'CpuOffload' from 'accelerate.hooks' (/home/phd/conda/envs/baddif/lib/python3.9/site-packages/accelerate/hooks.py)` 
How can I solve the problem, I hope I can get a reply from you.

**Comment by FrankCCCCC** [comment]
Hi, thank you for your interests. I've updated the content under ``diffuser`` folder. Please re-install ``diffusers`` library locally according to the ``install.sh`` script.
