### ISSUE TITLE
pipline init error

### ISSUE THREAD

**Issue by imomoe233** [IBM/BadDiffusion#8]
I meet some trouble like this.
Could u plz help me?What should i do?

image size: [32, 32]
Flattening the indices: 100%|██████████████████████████████████████████████████████████████████████████████████| 54000/54000 [00:02<00:00, 25379.76 examples/s]
Flattening the indices: 100%|████████████████████████████████████████████████████████████████████████████████████| 6000/6000 [00:00<00:00, 27657.79 examples/s]
Note that CHANNEL 0 - vmin: -0.9607846736907959 and vmax: 0.8666479587554932 | CHANNEL 1 - vmin: -0.9450985789299011 and vmax: 0.5450825691223145 | CHANNEL 2 - 
vmin: -0.9921569228172302 and vmax: 0.3882213830947876
datasetloader len: 60000
Downloading (…)ain/model_index.json: 100%|████████████████████████████████████████████████████████████████████████████████████| 180/180 [00:00<00:00, 30.8kB/s]
Downloading (…)f84deb80/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████| 699/699 [00:00<00:00, 240kB/s]
Downloading (…)cheduler_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:00<00:00, 86.6kB/s]
Downloading (…)ch_model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████| 143M/143M [00:13<00:00, 10.5MB/s]
Fetching 4 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:15<00:00,  3.92s/it]
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  8.80it/s] 
noise_sched.config.clip_sample = False
X:\Directory\code\BadDiffusion\baddiffusion.py:412: FutureWarning: Accessing config attribute `in_channels` directly via 'UNet2DModel' object attribute is deprecated. Please access 'in_channels' over 'UNet2DModel's config object instead, e.g. 'unet.config.in_channels'.
  (config.eval_sample_n, pipeline.unet.in_channels, pipeline.unet.sample_size, pipeline.unet.sample_size),
Traceback (most recent call last):
  File "X:\Directory\code\BadDiffusion\baddiffusion.py", line 584, in train_loop
    sampling(config, 0, pipeline)
  File "X:\Directory\code\BadDiffusion\baddiffusion.py", line 416, in sampling
    gen_samples(init=noise, folder="samples")
  File "X:\Directory\code\BadDiffusion\baddiffusion.py", line 375, in gen_samples
    pipline_res = pipeline(
  File "D:\Anaconda3\envs\sd\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: __call__() got an unexpected keyword argument 'init'

Traceback (most recent call last):
  File "X:\Directory\code\BadDiffusion\baddiffusion.py", line 657, in <module>
    pipeline = train_loop(config, accelerator, repo, model, get_pipeline, noise_sched, optimizer, dataloader, lr_sched, start_epoch=cur_epoch, start_step=cur_step)
  File "X:\Directory\code\BadDiffusion\baddiffusion.py", line 646, in train_loop
    sampling(config, 'final', pipeline)
  File "X:\Directory\code\BadDiffusion\baddiffusion.py", line 416, in sampling
    gen_samples(init=noise, folder="samples")
  File "X:\Directory\code\BadDiffusion\baddiffusion.py", line 375, in gen_samples
    pipline_res = pipeline(
  File "D:\Anaconda3\envs\sd\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: __call__() got an unexpected keyword argument 'init'
Traceback (most recent call last):
  File "X:\Directory\code\BadDiffusion\baddiffusion.py", line 657, in <module>
    pipeline = train_loop(config, accelerator, repo, model, get_pipeline, noise_sched, optimizer, dataloader, lr_sched, start_epoch=cur_epoch, start_step=cur_step)
  File "X:\Directory\code\BadDiffusion\baddiffusion.py", line 646, in train_loop
    sampling(config, 'final', pipeline)
  File "X:\Directory\code\BadDiffusion\baddiffusion.py", line 416, in sampling
    gen_samples(init=noise, folder="samples")
  File "X:\Directory\code\BadDiffusion\baddiffusion.py", line 375, in gen_samples
    pipline_res = pipeline(
  File "D:\Anaconda3\envs\sd\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: __call__() got an unexpected keyword argument 'init'

**Comment by FrankCCCCC** [comment]
Hi, thank you for your interests in my work. However, this issue should be caused by the improper ``diffusers`` library installation. Thus, please follow the installation process and use the customized ``diffusers`` library under the folder ``diffusers``.
